export type ClientFilterStatus = "active" | "inactive" | "paused";

export type ClientFilterRow = {
  id: string;
  image?: string;
  name: string;
  phone?: string;
  email?: string;
  city: string;
  neighborhood: string;
  gender: string;
  status: ClientFilterStatus;
  consultant: string;
  instructor: string;
  activity: string;
  birthDate?: string;
  debtCents?: number;
};

export type ContractDueRow = {
  id: string;
  clientId: string;
  image?: string;
  name: string;
  contract: string;
  dueDate: string;
  status: ClientFilterStatus;
};

export type BirthdayRow = {
  id: string;
  image?: string;
  name: string;
  birthDate: string;
  age?: number;
  status: ClientFilterStatus;
};

export type ClientFiltersState = {
  active: boolean;
  inactive: boolean;
  paused: boolean;
  city: string;
  neighborhood: string;
  gender: string;
  birthMonth: string;
  age: string;
  birthDate: string;
  hasDebt: boolean;
  overdueDebt: boolean;
  debtDueThisMonth: boolean;
  instructor: string;
  consultant: string;
  activity: string;
  boughtBetweenEnabled: boolean;
  boughtBetweenStart: string;
  boughtBetweenEnd: string;
  withValueEnabled: boolean;
  minValue: string;
  maxValue: string;
  startEnabled: boolean;
  startDate: string;
  startEndDate: string;
  dueEnabled: boolean;
  dueStart: string;
  dueEnd: string;
  cancelEnabled: boolean;
  cancelStart: string;
  cancelEnd: string;
  contractActiveEnabled: boolean;
  contractActive: string;
  contractInactiveEnabled: boolean;
  contractInactive: string;
};

export type ClientFiltersActions = {
  setActive: (value: boolean) => void;
  setInactive: (value: boolean) => void;
  setPaused: (value: boolean) => void;
  setCity: (value: string) => void;
  setNeighborhood: (value: string) => void;
  setGender: (value: string) => void;
  setBirthMonth: (value: string) => void;
  setAge: (value: string) => void;
  setBirthDate: (value: string) => void;
  setHasDebt: (value: boolean) => void;
  setOverdueDebt: (value: boolean) => void;
  setDebtDueThisMonth: (value: boolean) => void;
  setInstructor: (value: string) => void;
  setConsultant: (value: string) => void;
  setActivity: (value: string) => void;
  setBoughtBetweenEnabled: (value: boolean) => void;
  setBoughtBetweenStart: (value: string) => void;
  setBoughtBetweenEnd: (value: string) => void;
  setWithValueEnabled: (value: boolean) => void;
  setMinValue: (value: string) => void;
  setMaxValue: (value: string) => void;
  setStartEnabled: (value: boolean) => void;
  setStartDate: (value: string) => void;
  setStartEndDate: (value: string) => void;
  setDueEnabled: (value: boolean) => void;
  setDueStart: (value: string) => void;
  setDueEnd: (value: string) => void;
  setCancelEnabled: (value: boolean) => void;
  setCancelStart: (value: string) => void;
  setCancelEnd: (value: string) => void;
  setContractActiveEnabled: (value: boolean) => void;
  setContractActive: (value: string) => void;
  setContractInactiveEnabled: (value: boolean) => void;
  setContractInactive: (value: string) => void;
};
